Repository ucsb-cs156-f23/proj-organic-f23-6pm-1, pull requests merged in 2023-11, with the labels that each got.

#32 Fix typo in the footer
  frontend/src/main/components/Nav/Footer.js
  frontend/src/tests/components/Nav/Footer.test.js
Labels: 5

#33 Added Fixtures for Courses
  frontend/src/fixtures/coursesFixtures.js
Labels: 5, Merge Candidate

#34 Added CoursesForm with tests and storybook
  frontend/src/main/components/Courses/CoursesForm.js
  frontend/src/stories/components/Courses/CoursesForm.stories.js
  frontend/src/tests/components/Courses/CoursesForm.test.js
Labels: 10

#37 Added Create Page for Courses with storybook and tests
  frontend/src/main/pages/Courses/CoursesCreatePage.js
  frontend/src/stories/pages/Courses/CoursesCreatePage.stories.js
  frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
Labels: Merge Candidate, 10

#36 Implement delete staff from course operation for Courses and tests
  src/main/java/edu/ucsb/cs156/organic/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: 10

#35 Added Instructor Column to UserTable and Tests
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Users/UsersTable.test.js
Labels: FIXME - See code review, FIXME-PR description/screenshots

#47 Added GET(single) operation for Course
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: Merge Candidate, 10

#46 Erwan toggle endpoints
  src/main/java/edu/ucsb/cs156/organic/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/organic/controllers/UsersController.java
  src/test/java/edu/ucsb/cs156/organic/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/organic/controllers/UsersControllerTests.java
Labels: 10

#48 Added 'Courses' table to frontend and associated tests.
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/main/components/Utils/CoursesUtils.js
  frontend/src/stories/components/Courses/CoursesTable.stories.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
  frontend/src/tests/components/Utils/CoursesUtils.test.js
  frontend/stryker.conf.json
Labels: 10

#45 Modify DELETE Operation in Courses to work with ROLE_INSTRUCTOR
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: 10
